name: Terraform  VM Creation
run-name: Running VM Creation from ${{ github.ref }}

on:
    push:
    workflow_dispatch:
      inputs:   
       action_to_perform:
         required: false
         description: What do you want to do?
         type: choice
         options:
             - plan
             - apply
             - destroy
         default: plan

jobs:
    create-vm:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.SA_KEY }}
    
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
            version: '>= 363.0.0'
    
        - name: 'Use gcloud CLI'
          run: 'gcloud info'
                
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            cli_config_credentials_hostname: 'app.terraform.io'
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
        - name: create credentials file
          run: |
            echo ${{ secrets.SA_KEY }} >> credentails.json

        - name: Terraform Init
          run: |
            terraform init
        
        - name: Terraform plan
          run: |
            terraform plan
        
        - name: Terraform apply
          run: |
            terraform apply